<?php $configPath = $this->getConfigPath();?>
<?php $groupName  = $this->getGroupName(); ?>
<?php $fieldName  = $this->getFieldName(); ?>
<?php $inputFieldName = "groups[".$groupName."][fields][".$fieldName."][value]"; ?>
<?php 
$helper        = $this->helper('Qlicks\Updateproducts\Helper\Data');
$isEnabled     = $helper->getConfig($configPath);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store         = $storeManager->getStore()->getBaseUrl();
?>

<a href="<?=$store.'qlick/index/downloadfile'?>"><span>Download sample</span></a>

<script type="text/javascript">  

(function() {    

    require(["jquery"], function($) {

        $(document).ready(function($) {

            jQuery('#Qlicks_uploadconfig_Qlicks_file_up').next().remove();
            //console.log('fkld');
            
           }); 
      });
})();
</script>


